title: Card
loading-gif: /dev-valtech/images/blank.gif
variants:
- name: slim
  context:
    display:
      max-width: 220px
      max-height: 460px
- name: medium
  context:
    display:
      max-width: 360px
      max-height: 460px
- name: large
  context:
   display:
      max-width: 947px
      max-height: 460px
- name: mobile
  context:
    display:
      max-width: 220px
      max-height: 220px
    
    





